# Generated by Django 3.2 on 2024-06-05 20:24

import ckeditor_uploader.fields
from django.db import migrations, models
import src.news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('views', models.BigIntegerField(verbose_name='Просмотров')),
                ('likes', models.BigIntegerField(verbose_name='Понравилось')),
                ('dis_likes', models.BigIntegerField(verbose_name='Не понравилось')),
                ('image', models.ImageField(upload_to=src.news.models.get_file_path, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='news_articl_created_a034b3_idx'),
        ),
    ]
