# Generated by Django 3.2 on 2024-06-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена задания')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_task', models.BooleanField(default=False)),
                ('access_key', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='short_links.grouplink')),
            ],
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField()),
                ('endpoint', models.CharField(max_length=255, unique=True)),
                ('short_link', models.CharField(max_length=255)),
                ('passed', models.BooleanField(default=False)),
                ('task_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_links.tasklink')),
            ],
        ),
        migrations.CreateModel(
            name='LinkService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('default_link', models.CharField(max_length=255, unique=True)),
                ('api_link', models.CharField(max_length=255)),
                ('alias', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_links.grouplink')),
            ],
        ),
    ]
