# Generated by Django 3.2 on 2024-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('job', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('vk', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('gmail', models.EmailField(blank=True, max_length=254, verbose_name='')),
                ('yandex', models.EmailField(blank=True, max_length=254, verbose_name='')),
                ('tg', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('about', models.TextField(blank=True, verbose_name='users/avatar/')),
            ],
        ),
    ]
