# Generated by Django 3.2 on 2024-03-04 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='')),
                ('job', models.CharField(max_length=255, verbose_name='')),
                ('country', models.CharField(max_length=255, verbose_name='')),
                ('city', models.CharField(max_length=255, verbose_name='')),
                ('address', models.CharField(max_length=255, verbose_name='')),
                ('phone', models.CharField(max_length=255, verbose_name='')),
                ('vk', models.CharField(max_length=255, verbose_name='')),
                ('gmail', models.EmailField(max_length=254, verbose_name='')),
                ('yandex', models.EmailField(max_length=254, verbose_name='')),
                ('tg', models.CharField(max_length=255, verbose_name='')),
                ('avatar', models.ImageField(upload_to='media/users/avatars/')),
                ('about', models.TextField(verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
