# Generated by Django 3.2 on 2024-03-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_profile', '0003_auto_20240305_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/avatars/'),
        ),
    ]
